### ISSUE TITLE
Book generation and deployment issue

### ISSUE THREAD

**Issue by mhasoba** [mhasoba/TheMulQuaBio#132]
See https://github.com/mhasoba/TheMulQuaBio/pull/129#issuecomment-2376621770

TBD

**Comment by mhasoba** [comment]
**Automating Deployment with GitHub Actions**

Proposal to use GitHub Actions to automate the book build and deployment process:

1. **Set Up Workflow**: Create a GitHub Actions workflow that triggers on pushes to the main / master branch.

2. **Build the Book**: Configure the workflow to install Jupyter Book and build the project.

3. **Deploy**: Use the `peaceiris/actions-gh-pages` action or similar to deploy the contents of `_build/html` to the `gh-pages` branch.

**Example Workflow Snippet**:

```yaml
name: Deploy Jupyter Book

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Jupyter Book
        run: pip install -U jupyter-book

      - name: Build the book
        run: jupyter-book build .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
```
